# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d5fdca05e55dfa253c914ee75f36523554f249fe4963300c3395a66c69c31d4e7142466afdc1e883188b3d1b6e23345aec43969614c40c7fa69b108d3b3b82

test:
  secret_key_base: c55bd0d878718eda97f22608f3c810c91f6fc0b3c4572c96d12b9730ffce0adec2a552d2eebaa2e5340d81655706711e50ae01d8707e4b4d19b34bde045243a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
